name: Pull-Request

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install # switch to `npm ci` once eslint plugin has been published
      - run: npm run affected:lint
      - run: npm run affected:test
      - run: npm run affected:e2e:ci
